name: CI/CD using github
on: push
jobs:
  Job-Message-Actions:
    runs-on: ubuntu-latest
    steps:
     - name: installing java
       uses: actions/setup-java@v3
       with:
        java version: '17'
        distribution: 'termurin'

     - name: check
       run: |
         java -version
         javac -version

     - name: Clone Project
       uses: actions/checkout@v3

     - name: create class
       run: javac Welcomeeorld.java

     - name: compile and run
       run: java WelcomeWorld
